#!/bin/bash

set -u
set -e

tag=$1

worker_tag=$(gcloud container images list-tags \
			--filter="tags:$tag" \
			--format=json gcr.io/news-service-demo/news-worker-service)

app_tag=$(gcloud container images list-tags \
			--filter="tags:$tag" \
			--format=json gcr.io/news-service-demo/news-app-service)

printf "Tags:\n"
printf "   app   : %s\n" $(echo $app_tag | jq -r '.[0].digest')
printf "   worker: %s\n" $(echo $worker_tag | jq -r '.[0].digest')
printf "\n"

if [[ "$app_tag" == "[]" || "$worker_tag" == "[]" ]]; then
  printf "One of the image tags does not exist, aborting\n"
  exit 1
fi

printf "\nApplying terraform..."
terraform -chdir=./deployments/gcp apply -auto-approve



