#!/bin/bash

token=$(openssl rand -hex 16)
token_with_user="${1}:${token}"
user_token=$(echo -n $token_with_user | openssl base64)

echo 
echo 
echo "app config (configs/prod.yaml)"
echo "\"${1}\": \"${token}\""
echo 
echo 
echo "in curl, "
echo "token=\"${user_token}\""


