ALTER TABLE source OWNER TO dev;
ALTER TABLE story OWNER TO dev;
ALTER TABLE record OWNER TO dev;
ALTER TABLE account OWNER TO dev;
ALTER TABLE auth OWNER TO dev;
ALTER TABLE pref OWNER TO dev;
ALTER TABLE search OWNER TO dev;
ALTER TABLE run OWNER TO dev;


GRANT CONNECT ON DATABASE news TO dev;
GRANT ALL PRIVILEGES ON DATABASE news TO dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dev;