DROP TABLE IF EXISTS record CASCADE;
DROP TABLE IF EXISTS story CASCADE;
DROP TABLE IF EXISTS source CASCADE;
DROP TABLE IF EXISTS pref CASCADE;
DROP TABLE IF EXISTS run CASCADE;
DROP TABLE IF EXISTS search CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS auth CASCADE;
